name: 'Setup Python Dependencies'
description: 'Set up Python with caching and install common dependencies'
inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.11'
  extra-packages:
    description: 'Additional packages to install (space-separated)'
    required: false
    default: ''
  cache-key-suffix:
    description: 'Additional suffix for cache key'
    required: false
    default: 'common'

runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'
        cache-dependency-path: |
          .github/actions/setup-python-deps/requirements.txt
          
    - name: Cache pip packages
      uses: actions/cache@v3
      id: pip-cache
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ inputs.cache-key-suffix }}-${{ hashFiles('.github/actions/setup-python-deps/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-${{ inputs.cache-key-suffix }}-
          ${{ runner.os }}-pip-
    
    - name: Install common dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r .github/actions/setup-python-deps/requirements.txt
        if [ -n "${{ inputs.extra-packages }}" ]; then
          pip install ${{ inputs.extra-packages }}
        fi
    
    - name: Display installed packages
      shell: bash
      run: pip list
